# Dockerfile
FROM python:3.11-slim

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

WORKDIR /app

# Install system dependencies
RUN apt-get update && apt-get install -y \
    build-essential \
    default-libmysqlclient-dev \
    pkg-config \
    && apt-get clean

# Install Poetry
RUN pip install poetry

# Copy only the dependency files first to leverage Docker cache
COPY pyproject.toml poetry.lock /app/

# Install project dependencies
RUN poetry install

# Copy the rest of the application code
COPY . /app/

# Run migrations and start Gunicorn server
CMD ["sh", "-c", "poetry run python manage.py migrate && poetry run gunicorn project.wsgi:application --bind 0.0.0.0:8000"]
